apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}-realmd
  labels:
    app: {{ template "chart.name" . }}-realmd
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.realmd.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "chart.name" . }}-realmd
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "chart.name" . }}-realmd
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.realmd.initContainer.enabled }}
      initContainers:
        - name: wait-for-db
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z {{ template "chart.fullname" . }}-mysql-service:3306; do echo waiting for db; sleep 2; done; sleep 120;']
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-realmd
          image: "{{ .Values.realmd.image.repository }}:{{ .Values.realmd.image.tag }}"
          imagePullPolicy: {{ .Values.realmd.image.pullPolicy }}
          env:
            - name: CHART_FULLNAME
              value: {{ template "chart.fullname" . }}
            - name: DATABASE_SUFFIX
              value: "{{ .Values.wowVersion }}"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mangos-secret
                  key: "MYSQL_ROOT_PASSWORD"
            - name: MYSQL_USER          
              valueFrom:
                secretKeyRef:
                  name: "mangos-secret"
                  key: "MYSQL_USER"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "mangos-secret"
                  key: "MYSQL_PASSWORD"
          ports:
            - name: "mangos-realmd"
              containerPort: 3724
          volumeMounts:
            - name: mangos-realm
              mountPath: /tmp
          command: 
          resources:
{{ toYaml .Values.realmd.resources | indent 12 }}
    {{- with .Values.realmd.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.realmd.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.realmd.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: mangos-realm
        persistentVolumeClaim:
          claimName: {{ .Values.realmd.persistentVolume.existingClaimName }}