{{- define "secret.login" -}}
{{- $fullname := include "chart.fullname" . -}}
{{- $user := include "chart.generateUser" . -}}
{{- $password := include "chart.generateUserPassword" . -}}
{{ printf "%s-mysql-service;3306;%s;%s;realmd" $fullname $user $password }}
{{- end }}

{{- define "secret.world" -}}
{{- $fullname := include "chart.fullname" . -}}
{{- $user := include "chart.generateUser" . -}}
{{- $password := include "chart.generateUserPassword" . -}}
{{- $suffix := include "databaseSuffix" . -}}
{{ printf "%s-mysql-service;3306;%s;%s;mangos%s" $fullname $user $password $suffix }}
{{- end }}

{{- define "secret.character" -}}
{{- $fullname := include "chart.fullname" . -}}
{{- $user := include "chart.generateUser" . -}}
{{- $password := include "chart.generateUserPassword" . -}}
{{- $suffix := include "databaseSuffix" . -}}
{{ printf "%s-mysql-service;3306;%s;%s;character%s" $fullname $user $password $suffix }}
{{- end }}



{{- define "generateInfoschemaUser" -}}
{{- .Values.mysql.infoschemaUser | default "mysql.infoschema" -}}
{{- end -}}

{{- define "generateInfoschemaPassword" -}}
{{- .Values.mysql.infoschemaPassword | default (randAlphaNum 24) -}}
{{- end -}}


{{- define "databaseSuffix" -}}
{{- .Values.wowVersion -}}
{{- end -}}

{{- define "getPassword" }}
{{- .Values.mysql.rootPassword | default (randAlphaNum 24) -}}
{{- end }}

{{- define "generatePassword" -}}
{{- .Values.mysql.password | default (randAlphaNum 24) -}}
{{- end -}}

{{- define "generateUser" -}}
{{- .Values.mysql.user | default "mangos" -}}
{{- end -}}


apiVersion: v1
kind: Secret
metadata:
    name: mangos-secret
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: {{ include "getPassword" . | b64enc }}
    MYSQL_USER: {{ include "chart.generateUser" . | b64enc }}
    MYSQL_PASSWORD: {{ include "chart.generateUserPassword" . | b64enc }}
    MYSQL_INFOSCHEMA_USER: {{ include "generateInfoschemaUser" . | b64enc }}
    MYSQL_INFOSCHEMA_PASSWORD: {{ include "generateInfoschemaPassword" . | b64enc }}
    LOGIN_DATABASE_INFO: {{ include "secret.login" . | b64enc }}
    WORLD_DATABASE_INFO: {{ include "secret.world" . | b64enc }}
    CHARACTER_DATABASE_INFO: {{ include "secret.character" . | b64enc }}