{{- define "generateInfoschemaUser" -}}
{{- .Values.mysql.infoschemaUser | default "mysql.infoschema" -}}
{{- end -}}

{{- define "generateInfoschemaPassword" -}}
{{- .Values.mysql.infoschemaPassword | default (randAlphaNum 24) -}}
{{- end -}}


{{- define "databaseSuffix" -}}
{{- .Values.wowVersion -}}
{{- end -}}

{{- define "getPassword" }}
{{- .Values.mysql.rootPassword | default (randAlphaNum 24) -}}
{{- end }}

{{- define "generateMySQLUSERPassword" -}}
{{- .Values.mysql.MySQLUserPassword | default (randAlphaNum 24) -}}
{{- end -}}

{{- define "generateMYSQLUser" -}}
{{- .Values.mysql.MySQLUser | default "mangos" -}}
{{- end -}}


apiVersion: v1
kind: Secret
metadata:
    name: mangos-secret
    annotations:
      "helm.sh/resource-policy": keep
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: {{ include "getPassword" . | b64enc }}
    MYSQL_USER: {{ include "generateMYSQLUser" . | b64enc }}
    MYSQL_PASSWORD: {{ include "generateMySQLUSERPassword" . | b64enc }}
    MYSQL_INFOSCHEMA_USER: {{ include "generateInfoschemaUser" . | b64enc }}
    MYSQL_INFOSCHEMA_PASSWORD: {{ include "generateInfoschemaPassword" . | b64enc }}
    MYSQL_PRIVILEGED_USER_PASSWORD: {{ include "getPassword" . | b64enc }}