apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}-world
  labels:
    app: {{ template "chart.name" . }}-world
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.world.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "chart.name" . }}-world
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "chart.name" . }}-world
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.world.initContainer.enabled }}
      initContainers:
        - name: wait-for-db
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z {{ template "chart.fullname" . }}-mysql-service:3306; do echo waiting for db; sleep 2; done;']
        - name: wait-for-realmd
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z {{ template "chart.fullname" . }}-realmd-service:3724; do echo waiting for db; sleep 2; done;']
        - name: move-mangos-data
          image: busybox:latest
          command: ["/bin/sh", "-c", "cp -r /var/etc/mangos/* /etc/mangos/ && rm -rf /var/etc/mangos/*"]
          volumeMounts:
            - name: mangos-serverdata
              mountPath: /etc/mangos
            - name: var-etc-mangos
              mountPath: /var/etc/mangos
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-world
          image: "{{ .Values.world.image.repository }}:{{ .Values.world.image.tag }}"
          imagePullPolicy: {{ .Values.world.image.pullPolicy }}
          env:
            - name: CHART_FULLNAME
              value: {{ template "chart.fullname" . }}
            - name: DATABASE_SUFFIX
              value: "{{ .Values.wowVersion }}"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mangos-secret
                  key: "MYSQL_ROOT_PASSWORD"
            - name: MYSQL_USER          
              valueFrom:
                secretKeyRef:
                  name: "mangos-secret"
                  key: "MYSQL_USER"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "mangos-secret"
                  key: "MYSQL_PASSWORD"
          ports:
            - name: "mangos-world"
              containerPort: 8085
          volumeMounts:
            - name: mangos-configdata
              mountPath: /tmp
            - name: mangos-serverdata
              mountPath: /etc/mangos
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.world.resources | indent 12 }}
      volumes:
        - name: mangos-serverdata
          persistentVolumeClaim:
            claimName: {{ .Values.world.persistentVolume.serverdata.existingClaimName }}
        - name: mangos-configdata
          persistentVolumeClaim:
            claimName: {{ .Values.world.persistentVolume.configdata.existingClaimName }}
      {{- with .Values.world.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.world.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.world.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
