# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Version of WoW you want to create
# 0 - Vanilla         (Mangos Zero)
# 1 - Burning Crusade (Mangos One)
# 2 - Lich King       (Mangos Two)
# 3 - Cataclysm       (Mangos Three)
# 4 - Mists           (Mangos Four)
# 5 - Warlords        (Mangos Five)
wowVersion: 0

# Realm/auth server settings
realmd:
  initContainer:
    enabled: false
  replicaCount: 1

  persistentVolume:
    enabled: false
    existingClaimName: ""

  image:
    pullPolicy: IfNotPresent
    tag: latest
    repository:

  service:
    type: NodePort
    port: 3724

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# World server settings
world:
  initContainer:
    enabled: false
  replicaCount: 1

  persistentVolume:
    enabled: false
    serverdata:
      existingClaimName: ""
    configdata:
      existingClaimName: ""

  image:
    pullPolicy: IfNotPresent
    tag: latest
    repository:

  service:
    type: NodePort
    port: 8085

  resources:
    requests:
      cpu: 100m
      memory: 256Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Mysql server settings
mysql:
  replicaCount: 1

  rootPassword: "" # leave empty to use secret
  MySQLUser: "" # leave empty to use secret
  MySQLUserPassword: "" # leave empty to use secret
  database: mangos
  databaseRealmName: Karazhan
  dbRelease: Rel22
  rootHost: "%"

  persistentVolume:
    enabled: false
    existingClaimName: ""
  image:
    pullPolicy: IfNotPresent
    tag: latest
    repository:

  service:
    type: ClusterIP
    port: 3306

  resources:
    requests:
      cpu: 200m
      memory: 256Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
